services:
  robot-simulation:
    build: .
    env_file:
      - path: ./docker/default.env
        required: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY}:/root/.Xauthority
    privileged: true
    command: ros2 launch traxxas launch_sim.launch.py
    profiles:
      - simulation

  teleop:
    build: .
    env_file:
      - path: ./docker/default.env
        required: true
    command: ros2 run teleop_twist_keyboard teleop_twist_keyboard
    profiles:
      - do-not-start

  robot:
    build: .
    env_file:
      - path: ./docker/default.env
        required: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY}:/root/.Xauthority
    privileged: true
    command: ros2 launch traxxas rsp.launch.py
    depends_on:
      - joint_state_publisher
    profiles:
      - ""

  rviz:
    build: .
    env_file:
      - path: ./docker/default.env
        required: true
    command: rviz2 -d /usr/src/app/traxxas.rviz
    volumes:
      - ./traxxas.rviz:/usr/src/app/traxxas.rviz
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY}:/root/.Xauthority
    privileged: true
    profiles:
      - ""

  joint_state_publisher:
    build: .
    env_file:
      - path: ./docker/default.env
        required: true
    command: ros2 run joint_state_publisher_gui joint_state_publisher_gui
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY}:/root/.Xauthority
    privileged: true
    profiles:
      - ""
  
  cv_bridgex:
    build: /home/marc/Projects/ovcs/libraries/cv_bridgex
    env_file:
      - path: ./docker/default.env
        required: true 
    volumes:
      - /home/marc/Projects/ovcs/libraries/cv_bridgex:/usr/src/app
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
      - /dev/video2:/dev/video2
      - /dev/video3:/dev/video3
      - /dev/video4:/dev/video4
      - /dev/video5:/dev/video5
    privileged: true
    command: iex -S mix
    depends_on:
      - rviz
    profiles:
      - ""
